server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://47.100.45.101:3306/wxgzh?serverTimezone=Asia/Shanghai&useAffectedRows=true&useSSL=true&characterEncoding=utf8
    password: zhifa123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhifa.wxgzh.domain
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

wx:
  appid: wx44e91599e99be24a
  appsecret: eff5d9f3261d0b0b8337a77d2feae95c

  #appid: wx711bfa08f2b1ec2a
  #appsecret: cd68d8c7d2dd00f1554efbda769f62f2
  token: zhifa
  callback-url: http://www.zhifa.tech
  #callback-domain: http://fzft8c.natappfree.cc
  encoding-aes-key: by5Bam8DnWXWdEt1exy99jqatYouhAfHlTKo719ZBgE
